
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.*;
import java.sql.*;
import myapplication.ConnectDB;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jehan
 */
public class OSDSLoginPage extends javax.swing.JFrame {
    
    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null; 
    public OSDSLoginPage() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PLMBackgroundHolderPanel = new javax.swing.JPanel();
        PLMText = new javax.swing.JLabel();
        OfficeText = new javax.swing.JLabel();
        AndText = new javax.swing.JLabel();
        Title2 = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();
        BackgroundImage = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        FocusPlaceHolder = new javax.swing.JRadioButton();
        plmLogo = new javax.swing.JLabel();
        welcomeText = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        rememberCheckBox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        btnLoginButton = new SwingPackage.ButtonMaker();
        s3 = new SwingPackage.ButtonMaker();
        s1 = new SwingPackage.ButtonMaker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBounds(new java.awt.Rectangle(0, 0, 1280, 720));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        PLMBackgroundHolderPanel.setBackground(new java.awt.Color(255, 255, 255));
        PLMBackgroundHolderPanel.setLayout(null);

        PLMText.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        PLMText.setText("P A M A N T A S A N  N G  L U N G S O D  N G  M A Y N I L A ");
        PLMText.setName(""); // NOI18N
        PLMBackgroundHolderPanel.add(PLMText);
        PLMText.setBounds(60, 620, 430, 20);

        OfficeText.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        OfficeText.setText("OFFICE OF STUDENT");
        PLMBackgroundHolderPanel.add(OfficeText);
        OfficeText.setBounds(60, 560, 192, 20);

        AndText.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        AndText.setText("AND");
        PLMBackgroundHolderPanel.add(AndText);
        AndText.setBounds(320, 590, 34, 20);

        Title2.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        Title2.setForeground(new java.awt.Color(122, 0, 0));
        Title2.setText("SERVICES");
        PLMBackgroundHolderPanel.add(Title2);
        Title2.setBounds(360, 580, 160, 40);

        Title1.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        Title1.setForeground(new java.awt.Color(122, 0, 0));
        Title1.setText("DEVELOPMENT");
        PLMBackgroundHolderPanel.add(Title1);
        Title1.setBounds(60, 580, 260, 40);

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PLMBackgroundSmaller.png"))); // NOI18N
        BackgroundImage.setText("jLabel1");
        BackgroundImage.setPreferredSize(new java.awt.Dimension(1260, 790));
        PLMBackgroundHolderPanel.add(BackgroundImage);
        BackgroundImage.setBounds(-170, -60, 1260, 790);

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setPreferredSize(new java.awt.Dimension(400, 720));

        FocusPlaceHolder.setBackground(new java.awt.Color(255, 255, 255));
        FocusPlaceHolder.setOpaque(true);
        FocusPlaceHolder.setPreferredSize(new java.awt.Dimension(1, 1));

        plmLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plmLogo.png"))); // NOI18N

        welcomeText.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        welcomeText.setText("WELCOME !");

        usernameField.setBackground(new java.awt.Color(235, 235, 235));
        usernameField.setText("Username");
        usernameField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        usernameField.setCaretColor(new java.awt.Color(153, 153, 153));
        usernameField.setMargin(new java.awt.Insets(6, 6, 6, 6));
        usernameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFieldFocusLost(evt);
            }
        });
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        passwordField.setBackground(new java.awt.Color(235, 235, 235));
        passwordField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });

        rememberCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rememberCheckBox.setForeground(new java.awt.Color(122, 0, 0));
        rememberCheckBox.setText("REMEMBER ME");
        rememberCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rememberCheckBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(122, 0, 0));
        jLabel4.setText("FORGOT PASSWORD?");

        btnLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginButton.setText("LOG-IN");
        btnLoginButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnLoginButton.setRadius(15);
        btnLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginButtonMouseClicked(evt);
            }
        });
        btnLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginButtonActionPerformed(evt);
            }
        });

        s3.setBackground(new java.awt.Color(0, 153, 51));
        s3.setColor(new java.awt.Color(0, 153, 51));
        s3.setColorClick(new java.awt.Color(0, 153, 51));
        s3.setColorOver(new java.awt.Color(77, 166, 50));
        s3.setRadius(50);
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });

        s1.setColor(new java.awt.Color(168, 34, 34));
        s1.setColorClick(new java.awt.Color(168, 34, 34));
        s1.setColorOver(new java.awt.Color(204, 49, 49));
        s1.setRadius(50);
        s1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s1MouseClicked(evt);
            }
        });
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FocusPlaceHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(LoginPanelLayout.createSequentialGroup()
                                    .addComponent(rememberCheckBox)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4))
                                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(passwordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 61, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                        .addComponent(plmLogo)
                        .addGap(187, 187, 187))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                        .addComponent(welcomeText)
                        .addGap(155, 155, 155))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                        .addComponent(btnLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FocusPlaceHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plmLogo)
                .addGap(18, 18, 18)
                .addComponent(welcomeText)
                .addGap(75, 75, 75)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rememberCheckBox)
                    .addComponent(jLabel4))
                .addGap(43, 43, 43)
                .addComponent(btnLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PLMBackgroundHolderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PLMBackgroundHolderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTextField1ActionPerformed

    private void rememberCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rememberCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rememberCheckBoxActionPerformed

    private void fTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTextField3ActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed

    }//GEN-LAST:event_usernameFieldActionPerformed

    private void usernameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFieldFocusGained
        if(usernameField.getText().equals("Username")){
            usernameField.setText("");
        }
    }//GEN-LAST:event_usernameFieldFocusGained

    private void usernameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFieldFocusLost
        if(usernameField.getText().equals("")){
            usernameField.setText("Username");  
        }
    }//GEN-LAST:event_usernameFieldFocusLost

    private void btnLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginButtonActionPerformed

        
    }//GEN-LAST:event_btnLoginButtonActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        setState(OSDSLoginPage.ICONIFIED);
    }//GEN-LAST:event_s3ActionPerformed

    private void s1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_s1MouseClicked

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_s1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        conn = ConnectDB.Connect();
        passwordField.setText("Password");
        passwordField.setEchoChar((char) 0);
    }//GEN-LAST:event_formWindowActivated

    private void btnLoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginButtonMouseClicked
//        passwordField.setEchoChar((char) 0);
        
        String enteredUsername = usernameField.getText();
        String enteredPassword = passwordField.getText();
        if (enteredUsername.isEmpty() || enteredPassword.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter both your username and password.", "Empty Fields", JOptionPane.WARNING_MESSAGE);
            return; 
        }
            try{
                ps = conn.prepareStatement("SELECT * FROM app.USER_CREDENTIALS WHERE username = '" + enteredUsername + "' AND password = '" + enteredPassword + "'");
                rs = ps.executeQuery();

                if (rs.next()) {
                // Successful login
                String userName = rs.getString("username");
                
                dispose();
                OSDSDashBoard db = new OSDSDashBoard(userName);
                db.show();
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid username or password. Please try again.");
                    passwordField.setText("");
                }

            }catch (Exception e) {
                JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnLoginButtonMouseClicked

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        if (passwordField.getPassword().length == 0) {
            passwordField.setText("Password");
            passwordField.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_passwordFieldFocusLost

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained

        passwordField.setEchoChar('*'); // Set the echo character for masking

        String currentText = String.valueOf(passwordField.getPassword());
        if (currentText.equals("Password")) {
            passwordField.setText(""); // Clear only if placeholder is present
        }
    }//GEN-LAST:event_passwordFieldFocusGained

    
    /**
     * @param args the command line arguments
     */


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OSDSLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OSDSLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OSDSLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OSDSLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OSDSLoginPage().setVisible(true);
            }
            
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AndText;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JRadioButton FocusPlaceHolder;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel OfficeText;
    private javax.swing.JPanel PLMBackgroundHolderPanel;
    private javax.swing.JLabel PLMText;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private SwingPackage.ButtonMaker btnLoginButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel plmLogo;
    private javax.swing.JCheckBox rememberCheckBox;
    private SwingPackage.ButtonMaker s1;
    private SwingPackage.ButtonMaker s3;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}


